spring:
  application:
    name: store
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
  jpa:
    show-sql: true
