spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessToken: 300 # 5 min.
    refreshToken: 604800 # 7 days
